security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
    admin:
        pattern: ^/failrun/admin
        provider: app_user_provider
        form_login:
            login_path: app_failrun_admin_login
            check_path: app_failrun_admin_login
            default_target_path: app_failrun_admin_panel
        logout:
            path: app_failrun_admin_logout
            target: app_failrun_admin_login
    main:
        lazy: true
        provider: app_user_provider
        stateless: true
        jwt: ~

    access_control:
        - { path: ^/failrun/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/failrun/admin, roles: ROLE_ADMIN }
        - { path: ^/failrun/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/failrun/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/failrun/api/test, roles: PUBLIC_ACCESS }
        - { path: ^/failrun/api, roles: IS_AUTHENTICATED_FULLY }