security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        admin:
            pattern: ^/failrun/admin
            provider: app_user_provider
            form_login:
                login_path: app_failrun_admin_login
                check_path: app_failrun_admin_login
                default_target_path: app_failrun_admin_panel
            logout:
                path: app_failrun_admin_logout
                target: app_failrun_admin_login
        main:
            lazy: true
            provider: app_user_provider
            stateless: true
            jwt: ~
            custom_authenticators:
                - App\Security\ApiKeyAuthenticator

    access_control:
        - { path: ^/failrun/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/failrun/admin/api-keys, roles: ROLE_ADMIN }
        - { path: ^/failrun/admin, roles: [ROLE_ADMIN, ROLE_MODERATOR] }
        - { path: ^/failrun/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/failrun/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/failrun/api/test, roles: PUBLIC_ACCESS }
        - { path: ^/failrun/api/key-test, roles: ROLE_API }
        - { path: ^/failrun/api/get-games, roles: PUBLIC_ACCESS }
        - { path: ^/failrun/api/get-game-clips, roles: PUBLIC_ACCESS }
        - { path: ^/failrun/api/get-clip-info, roles: PUBLIC_ACCESS }
        - { path: ^/failrun/api/get-random-clips, roles: PUBLIC_ACCESS }
        - { path: ^/failrun/api/get-top-rated-clips, roles: PUBLIC_ACCESS }
        - { path: ^/failrun/api/get-random-clip, roles: ROLE_API }
        - { path: ^/failrun/api/get-top-rated-clip, roles: ROLE_API }
        - { path: ^/failrun/api/get-stats, roles: ROLE_API }
        - { path: ^/failrun/api/get-recent-clips, roles: ROLE_API }
        - { path: ^/failrun/api, roles: IS_AUTHENTICATED_FULLY }